attempts: 3
trigger: '2020-11-03 13:17'
event_url: 'https://omega.ntnu.no/events/show/541'
users:
    markskag: 'Passord123'

user_agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36'
