attempts: 10
trigger: '2020-11-02 21:10'
event_url: 'https://omega.ntnu.no/events/show/541'
users:
    user1: 'pw1'
    user2: 'pw2'
    user3: 'pw3'

user_agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36'