user:
    username: "markskag"
    password: "1231231"
selector:
    aksjenm_entry_id: "#username"
    mailform_id: "#email"
    button_id: "#ActionButton_0"
    password_id: "#password-label"
    searchbox_id: "#quicktrade__ticker"
request:
    trade: "https://aksjeligaen.e24.no/server/game/trade"
    search: "https://aksjeligaen.e24.no/server/secure/suggest?group=STOCK_GAME&query={}"